base_url = "https://bit-devs-barcelona.github.io"
title = "BitDevs Barcelona"
description = "BitDevs Barcelona és una comunitat a l'àrea de Barcelona (Catalunya) per aquells interessats en la investigació i el desenvolupament de Bitcoin i protocols relacionats."
compile_sass = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
build_search_index = false

[markdown]
highlight_code = true
external_links_target_blank = true

[extra]
icons = [
  {icon = "github", link = "https://github.com/Bit-Devs-Barcelona/bit-devs-barcelona.io"}
]

